# Analisis para saber si se van a alinear o se pueden alinear adecuadamente los candidatos

In [62]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sys
sys.path.append('../')
sys.path.append('../math_tricks/')
import funciones_CLICK as fc
from scipy.spatial.distance import pdist, squareform
import multiprocessing
from functools import partial
import warnings
warnings.simplefilter("ignore")

%matplotlib inline

--------------------------------------------
__Encontramos que cuando se rota y traslada [referencia](https://academic.oup.com/nar/article/45/1/e5/2871113), hay que calcular la distancia de UN residuo $A_i$ VS todos los $B_j$ y quedarnos con la pareja $(A_i,B_j)$ tal que su distancia sea menor a 3.5 A y si hay mas de uno te quedas con el menor!!__

## Encontrar matcheo de residuo a residuo, en lo que calcula la rotacion y traslacion.

In [63]:
new_df_cliques1 = pd.read_pickle('../clique1.pkl')
new_df_cliques2 = pd.read_pickle('../clique2.pkl')

candidatos = pd.read_pickle('../parejas.pkl')

df_atoms1 = pd.read_pickle('../clique1_df_atributos.pkl')
df_atoms2 = pd.read_pickle('../clique2_df_atributos.pkl')

rmsd = pd.read_pickle("../df_alineados.pkl").reset_index(drop=True)

In [64]:
pd.DataFrame(candidatos) # RESIDUOS

         0        1
0 98.0000  160.0000
1 99.0000  161.0000
2 100.0000 121.0000
3 86.0000  156.0000
4 87.0000  157.0000
5 88.0000  158.0000
6 89.0000  159.0000

In [70]:
df_atoms1.iloc[342]

atom_number       343
atom_name         C
residue_name      ASP
residue_number    129
vector            [16.469, 64.314, 18.354]
ngb               [85, 86, 87, 98, 99, 100, 101, 102, 103, 104, 105, 106, 108, 126, 127, 128, 130, 131]
Name: 342, dtype: object

In [66]:
rmsd.sort_values('distancia',ascending=True).head()

   distancia  candigatos  cand_1  cand2
0 0.3368      (485, 796)  485     796
1 0.5361      (136, 279)  136     279
2 0.9679      (251, 710)  251     710
3 1.0505      (342, 300)  342     300
4 1.1205      (197, 834)  197     834

In [67]:
rmsd

    distancia  candigatos  cand_1  cand2
0  0.3368      (485, 796)  485     796
1  0.5361      (136, 279)  136     279
2  0.9679      (251, 710)  251     710
3  1.0505      (342, 300)  342     300
4  1.1205      (197, 834)  197     834
5  1.3781      (121, 243)  121     243
6  1.4080      (180, 847)  180     847
7  1.5792      (476, 377)  476     377
8  1.6667      (27, 2)     27      2
9  1.6835      (383, 605)  383     605
10 1.7145      (306, 622)  306     622
11 1.7262      (221, 691)  221     691
12 1.7435      (325, 660)  325     660
13 1.9313      (210, 675)  210     675
14 1.9357      (229, 683)  229     683
15 2.0076      (414, 519)  414     519
16 2.0520      (317, 638)  317     638
17 2.0740      (290, 579)  290     579
18 2.1059      (397, 545)  397     545
19 2.1761      (390, 562)  390     562
20 2.1820      (286, 533)  286     533
21 2.2371      (102, 161)  102     161
22 2.3191      (277, 716)  277     716
23 2.3316      (439, 77)   439     77
24 2.3475      (175, 840)  175     840
25 2.5319      (166, 871)  166     871
26 2.5463      (146, 328)  146     328
27 2.5647      (448, 386)  448     386
28 2.6547      (86, 152)   86      152
29 2.6759      (205, 669)  205     669
30 2.7482      (74, 193)   74      193
31 2.8254      (66, 52)    66      52
32 2.8589      (357, 249)  357     249
33 2.8767      (464, 371)  464     371
34 2.8870      (310, 614)  310     614
35 2.9120      (19, 10)    19      10
36 2.9429      (490, 808)  490     808
37 2.9518      (58, 42)    58      42
38 2.9578      (50, 29)    50      29
39 2.9647      (153, 323)  153     323
40 3.0654      (350, 291)  350     291
41 3.2608      (107, 206)  107     206

In [38]:
%%time
a_1 = df_atoms1[df_atoms1.atom_name == 'CA'].vector.values

lista_vectores_gorro = []
for bari in new_df_cliques1.baricentro_clique.values:
    lista_pre_vectores = []

    for coord in a_1:
        lista_pre_vectores.append(coord - bari)

    lista_vectores_gorro.append(lista_pre_vectores)

CPU times: user 14 ms, sys: 0 ns, total: 14 ms
Wall time: 13.3 ms

In [22]:
vectores_gorro_proteina_1 = pd.DataFrame(lista_vectores_gorro)

In [23]:
%%time
a_2 = df_atoms2[df_atoms2.atom_name == 'CA'].vector.values

lista_vectores_gorro = []
for bari in new_df_cliques2.baricentro_clique.values:
    lista_pre_vectores = []
    for coord in a_2:
        lista_pre_vectores.append(coord - bari)

    lista_vectores_gorro.append(lista_pre_vectores)

CPU times: user 25.4 ms, sys: 39 µs, total: 25.5 ms
Wall time: 24.7 ms

In [24]:
vectores_gorro_proteina_2 = pd.DataFrame(lista_vectores_gorro)

In [26]:
vectores_gorro_proteina_1.shape

(553, 71)

In [27]:
for i,j in enumerate(rmsd.columns):
    print(i,j)

0 rmsd
1 candidatos
2 matriz_rotacion
3 candidato_clique_1
4 candidato_clique_2

In [28]:
for i,j in enumerate(new_df_cliques1.columns):
    print(i,j)

0 0
1 1
2 2
3 3
4 4
5 5
6 6
7 ss_0
8 ss_1
9 ss_2
10 ss_3
11 ss_4
12 ss_5
13 ss_6
14 coord_clique_0
15 coord_clique_1
16 coord_clique_2
17 coord_clique_3
18 coord_clique_4
19 coord_clique_5
20 coord_clique_6
21 matriz_coordenadas
22 baricentro_clique
23 vec_gorro_0
24 vec_gorro_1
25 vec_gorro_2
26 vec_gorro_3
27 vec_gorro_4
28 vec_gorro_5
29 vec_gorro_6
30 vectores_gorro
31 distancia_promedio

In [36]:
# idx = id_so = 354
# so = 0.0
idx = 0
df_rmsd = rmsd.values
df_new_df_clique1 = new_df_cliques1.values
df_new_df_clique2 = new_df_cliques2.values
df_vectores_gorro_proteina_1 = vectores_gorro_proteina_1.values
df_vectores_gorro_proteina_2 = vectores_gorro_proteina_2.values

atoms1 = df_atoms1.atom_number.values
atoms2 = df_atoms2.atom_number.values
number_of_residues = df_atoms1.shape[0]

protein_to_compare = np.array([i for i in df_atoms2.vector.values])

if so == 1.0:
    id_so = idx
    print(so, id_so)
    print('////' * 20)


clique_in_protein_1 = df_rmsd[idx, 3]  # se extrae la info de los candidatos
clique_in_protein_2 = df_rmsd[idx, 4]

# se obtienen el numero de residuo de los candidatos
los_del_clique_1 = df_new_df_clique1[clique_in_protein_1, [0, 1, 2, 3, 4, 5, 6]]
los_del_clique_2 = df_new_df_clique1[clique_in_protein_2, [0, 1, 2, 3, 4, 5, 6]]

matriz_rotacion = df_rmsd[idx, 2]  # se obtiene la matriz de rotacion de los cliques candidatos

# se obtienen los vectores gorro de la proteina a rotar y trasladar
vector_gorro = df_vectores_gorro_proteina_1[clique_in_protein_1]
# se aplica la rotacion a vectores gorro
coord_vectores_rotados = [np.matmul(matriz_rotacion, i.reshape(3, 1)).T[0] for i in vector_gorro]
# se obtiene el baricentro de la proteina 2
baricentro_proteina_2 = df_new_df_clique2[clique_in_protein_2, 22]
# se suma el baricentro a vectores rotados de la proteina 1
protein_trasladado_rotado = coord_vectores_rotados + baricentro_proteina_2  # nuevas coordendas proteina 1
# se quitan residuos que pertenezcan al clique candidato para calcular la distancia y emparejar al mejor.
protein_trasladado_rotado_sin_clique = np.delete(protein_trasladado_rotado, los_del_clique_1, 0)
protein_to_compare_sin_clique = np.delete(protein_to_compare, los_del_clique_2, 0)
# numeros de atomos
atom_numbers1 = np.delete(atoms1, los_del_clique_1, 0)
atom_numbers2 = np.delete(atoms2, los_del_clique_2, 0)

residuos_match = []  # aqui se guardan las parejas de residuos

# se itera por cada residuo ya rotado y trasladado
for residuo_not_in_clique, res_1 in zip(protein_trasladado_rotado_sin_clique, atom_numbers1):
          for residuo, res_2 in zip(protein_to_compare_sin_clique, atom_numbers2):
            distancia = pdist(np.array([residuo_not_in_clique, residuo]), metric='euclidean').item()
            if distancia < 3.5:
                continue
#                 list_cand =[pdist(np.array([residuo_not_in_clique, res_ngb.coord]), metric='euclidean').item()
#                      for res_ngb in residuo.ngb]
#                 break
#                 residuos_match.append([distancia, (res_1, res_2)])

df = pd.DataFrame(residuos_match, columns=['distancia', 'candigatos'])

a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a
a

In [47]:
id_so = 0
so = 0.0

def align_residues(idx, so):

    df_rmsd = rmsd.values
    df_new_df_clique1 = new_df_cliques1.values
    df_new_df_clique2 = new_df_cliques2.values
    df_vectores_gorro_proteina_1 = vectores_gorro_proteina_1.values
    df_vectores_gorro_proteina_2 = vectores_gorro_proteina_2.values

    atoms1 = df_atoms1[df_atoms1.atom_name == 'CA'].atom_number.values
    atoms2 = df_atoms2[df_atoms1.atom_name == 'CA'].atom_number.values
    number_of_residues = df_atoms1[df_atoms1.atom_name == 'CA'].shape[0]
    
    protein_to_compare = np.array([i for i in df_atoms2[df_atoms2.atom_name == 'CA'].vector.values])
    
    clique_in_protein_1 = df_rmsd[idx, 3]  # se extrae la info de los candidatos
    clique_in_protein_2 = df_rmsd[idx, 4]

    # se obtienen el numero de residuo de los candidatos
    los_del_clique_1 = df_new_df_clique1[clique_in_protein_1, [0, 1, 2, 3, 4, 5, 6]]
    los_del_clique_2 = df_new_df_clique1[clique_in_protein_2, [0, 1, 2, 3, 4, 5, 6]]

    matriz_rotacion = df_rmsd[idx, 2]  # se obtiene la matriz de rotacion de los cliques candidatos

    # se obtienen los vectores gorro de la proteina a rotar y trasladar
    vector_gorro = df_vectores_gorro_proteina_1[clique_in_protein_1]
    # se aplica la rotacion a vectores gorro
    coord_vectores_rotados = [np.matmul(matriz_rotacion, i.reshape(3, 1)).T[0] for i in vector_gorro]
    # se obtiene el baricentro de la proteina 2
    baricentro_proteina_2 = df_new_df_clique2[clique_in_protein_2, 22]
    # se suma el baricentro a vectores rotados de la proteina 1
    protein_trasladado_rotado = coord_vectores_rotados + baricentro_proteina_2  # nuevas coordendas proteina 1
    # se quitan residuos que pertenezcan al clique candidato para calcular la distancia y emparejar al mejor.
    protein_trasladado_rotado_sin_clique = np.delete(protein_trasladado_rotado, los_del_clique_1, 0)
    protein_to_compare_sin_clique = np.delete(protein_to_compare, los_del_clique_2, 0)
    # numeros de atomos
    atom_numbers1 = np.delete(atoms1, los_del_clique_1, 0)
    atom_numbers2 = np.delete(atoms2, los_del_clique_2, 0)

    residuos_match = []  # aqui se guardan las parejas de residuos

    # se itera por cada residuo ya rotado y trasladado
 
    for residuo_not_in_clique, res_1 in zip(protein_trasladado_rotado_sin_clique, atom_numbers1):
        for residuo, res_2 in zip(protein_to_compare_sin_clique, atom_numbers2):
            distancia = pdist(np.array([residuo_not_in_clique, residuo]), metric='euclidean').item()
            if distancia < 3.5:
                residuos_match.append([distancia, (res_1, res_2)])

    df = pd.DataFrame(residuos_match, columns=['distancia', 'candigatos'])
    df = df.sort_values('distancia')
    df['cand1'] = df.candigatos.str[0]
    df['cand2'] = df.candigatos.str[1]

    c1 = []
    c2 = []
    cand_n = []
    for i in df.values:

        if (i[2] in c1) or (i[3] in c2) or (i[0] > 3.5):
            continue
        else:
            c1.append(i[2])
            c2.append(i[3])
            cand_n.append(i)

    so_temp = len(cand_n) / number_of_residues

    return idx, so_temp

In [52]:
id_so = 0
so = 0.0
for i in np.arange(len(df_rmsd))[:400]:
    id_so, so_temp = (align_residues(i,so))
    if so <= so_temp:
        so = so_temp
        id_so = i
        print(id_so,so)
    if so == 1:
        break

0 0.3380281690140845
1 0.647887323943662
248 0.7605633802816901
249 0.7605633802816901
250 1.0

In [30]:
%%time
align_residues(143,0)

CPU times: user 97.9 ms, sys: 4.04 ms, total: 102 ms
Wall time: 98.6 ms

143

In [31]:
((0.80 * 33740)/60)/60

7.497777777777778

In [32]:
((0.80 * 500)/60)

6.666666666666667

In [31]:
# p = multiprocessing.Pool(multiprocessing.cpu_count()-1)

# id_so = p.map(partial(align_residues, so=so), np.arange(len(df_rmsd))[:100])

# p.close()
# p.join()

# print(id_so)

In [ ]:
    def R_ij(i, j, a1=0, a2=0):
        """Recuerda que 0-->1,1-->2,2-->2 en los indices de R
        a1,a2 corresponden a que atomo quieren que se compare
        """
        idx_vec_gorro1, idx_vec_gorro2 = 2, 2 + num_cliques
        valor = sum(  # VECTORES GORRO AGARRARLOS!!!
            [array_cliques1[:, k][a1][i] * array_cliques2[:, k][a2][j] for k in range(idx_vec_gorro1, idx_vec_gorro2)])
        return (valor)